version: '3.9'

volumes:
  typesense: ~

endpoints:
  labels:
    dev.okteto.com/endpoints: https://typesense-${OKTETO_NAMESPACE}.${OKTETO_DOMAIN}
  rules:
    - path: /
      service: typesense
      port: 8108

services:
  typesense:
    image: typesense/typesense:0.23.1
    volumes:
      - typesense:/tmp
    ports:
      - 8108:8108
    command:
      - "--data-dir=/tmp"
      - "--api-key=${TYPESENSE_API_KEY}"
      - "--enable-cors"
    healthcheck:
      test: ["CMD", "curl -f http://localhost:8108 || exit 1"]
      timeout: 30s
      interval: 1m
      retries: 3
