version: '3.9'

volumes:
  typesense: ~

services:
  typesense:
    image: typesense/typesense:0.23.1
    volumes:
      - typesense:/data
    ports:
      - 8108:8108
    command:
      - '--data-dir=/data'
      - '--api-key=Hu52dwsas2AdxdE'
      - '--enable-cors'
    healthcheck:
      test: ["CMD", "curl -f http://localhost:8108 || exit 1"]
      timeout: 30s
      interval: 1m
      retries: 3
