version: '3.9'

volumes:
  typesense: ~

endpoints:
  labels:
    dev.okteto.com/endpoints: https://typesense-${OKTETO_NAMESPACE}.${OKTETO_DOMAIN}
  rules:
    - path: /
      service: typesense
      port: 8108

services:
  typesense:
    build: .
    volumes:
      - typesense:/data
    ports:
      - 8108:8108
